// Inclucding ATMega64 library
.include "m64def.inc"

//Define r16 as temp-used register 
.def temp = r16

//Setting address of Main program in 0x00
.org 0x00
rjmp Main
.org 0x60 // after all registers of micro

//Starting main function
Main:

	//Setting stack pointer address after ending ram 
	ldi temp,low(ramend)
	out spl,temp
	ldi temp, high(ramend)
	out sph,temp

	//Setting all PORTC pins to output
	ldi temp,0xff
	out ddrc,temp
	
	ldi temp,0x01

//Main loop of program
loop:
	//Setting temp to 0x01 if it reached to 0x00 
	//to avoid unwanted 1s blackout! 
	subi temp,0x00
	breq zero
	//Writing on PORTC
	out portc,temp
	rol temp
	rjmp delay

zero:
	ldi temp,0x01
	out portc,temp
	rol temp


// Generated by delay loop calculator
// at http://www.bretmulvey.com/avrdelay.html
//
// Delay 8 000 000 cycles
// 1s at 8.0 MHz
delay:    
	ldi  r18, 41
    ldi  r19, 150
    ldi  r20, 128
L1: 
	//Generating delay...
	//NOTE: The whole delay genearation code takes 10 cycles.
	dec  r20
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1
	rjmp loop
